# Site
name: "APEXPATH -> A=Always P=Provide Ex=Excellence Path"
title: "APEXPATH ! Always Provide Excellence Path"
description: "In this ever changing world of technology, we are in the midst of a very exciting phase and probably never experienced before.I felt writing this blog would be an excellent way for me to share my experiences with all young and talented programmers out there, specifically ones which excite me."
logo: 'assets/images/small_logo.png'
favicon: 'assets/images/logo.png'
large_logo: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-106748707-1'
disqus: 'apexpath'
mailchimp-list: ''
include: ["_pages"]
permalink: /blog/post/:title/

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  munna:
    name: Munna Bhakta
    display_name: Munna Bhakta    
    #avatar: 'assets/images/avatar.png'
    gravatar: 36324185a1649b4ac39cd3554bedbf40
    email: wowthemesnet@gmail.com
    web: http://munnabhakta.com
    twitter: https://twitter.com/munnabhakta
    description: "Having more than 10 years of experiance in Web Development, GIS Development, Desktop Development"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
